### ISSUE TITLE
Crashes on World Load 1.19.2 Forge - NO EXTRA MODS

### ISSUE THREAD

**Issue by Rtificer** [Jarva/Ars-Additions#1]
It crashes upon pressing 'create world'

Loading into a already generated world freezes the game indefinitely with 0% generation percentage, with a weird pattern.
![2024-06-15_15 31 26](https://github.com/Jarva/Ars-Additions/assets/145673765/06e751c1-d0f0-40a6-8868-4f26a3e143f2)

**Comment by Jarva** [comment]
Do you have any logs you can provide?
