### ISSUE TITLE
Tablet of locate structure

### ISSUE THREAD

**Issue by ashebor** [Jarva/Ars-Additions#11]
there is litterally no information on how to actually utilize this included anywhere in the mod or on any page where ars additions is downloadable from

i understand that i need to augment it but with what for what structures, without info its impossible to actually know what to do

**Comment by Jarva** [comment]
Press U on the tablet to see its augments in JEI. These will be added to the book in the future.

**Comment by ashebor** [comment]
Thank you!

Alas not quite what i was hoping i could find with it, ie dungeons for spawners, but useful none the less

**Comment by Jarva** [comment]
Unfortunately dungeons aren't structures, they instead use worldgen features which make them harder to integrate
