### ISSUE TITLE
[1.21.1][Neoforge] Game crashes when looting Explorer Warp Scroll

### ISSUE THREAD

**Issue by ffuentesm** [Jarva/Ars-Additions#12]
ars_additions-1.21.1-21.1.4.jar
ars_nouveau-1.21.1-5.3.4-all.jar
Neoforge: 21.1.83
CrashLog: https://pastebin.com/TpdF0v0u

As the title says, it seems that when I try to remove the explorer Scroll from the loot chest, the game crashes. Once I reload the game, I will sometimes have the scroll on my inventory, but sometimes it vanishes.

**Comment by Jarva** [comment]
Fixed in 21.1.5 https://legacy.curseforge.com/minecraft/mc-mods/ars-additions/files/5963794
