### ISSUE TITLE
[1.20.1 Forge] Startup of MC client stops unexpectedly

### ISSUE THREAD

**Issue by templeofshadow** [Jarva/Ars-Additions#2]
First, to get this out of the way, this isn't a _crash_, per se. Or at least, MC nor Forge recognize it as such. Because of this, I don't have a crash report. But, I do have latest.log:
[latest.log](https://github.com/user-attachments/files/15988896/latest.log)

As you can see, it doesn't give a particular error, it doesn't give a crash report, it just stops, immediately after the line: 
`[26Jun2024 08:15:02.643] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 188 Datafixer optimizations took 111 milliseconds`

This only happens with Ars Additions enabled. I have had it do this multiple times, and it seems to stop when I disable Ars Additions. It always stops at the [com.mojang.datafixers.DataFixerBuilder/] line in the log.

For the record, I have all dependencies installed, along with some 190-ish other mods. As aformentioned, this issue only comes up with this mod. My Ars Additions version is 1.5.1.

Let me know if you need any other info.

**Comment by Jarva** [comment]
Hi there, can you provide your Forge version and a link to your modpack to see if I can replicate the issue?

**Comment by Jarva** [comment]
From reading your log file, it seems your version of Ars Nouveau is outdated, can you try update it?

You have version 4.9.0 and Ars Additions requires 4.10.0 or higher, with the latest being 4.12.1

**Comment by templeofshadow** [comment]
Yeah, just tried it and it worked. Apparently the "latest" version on Modrinth is outdated, so I pulled 4.12.1 from curseforge and it works fine. _Sigh_, sorry for taking your time, and thanks.

**Comment by Jarva** [comment]
That's all good, now I know what to look for when this issue pops up, thanks for the bug report
