### ISSUE TITLE
Item's not removed from Jar of Miner's Wisom

### ISSUE THREAD

**Issue by SeanCreations15** [Jarva/Ars-Additions#6]
Hey,

When holding an item that is enabled in the Jar of Miner's Wisdom in my off hand, and attempting to remove it, I see the message "Item Removed" But when hovering over the Jar, I can see its still in there, and mining it still voids it.

**Comment by Jarva** [comment]
I think this should be fixed in 21.1.0, but I've lost track of everything in there, let me know if it's still happening

**Comment by SeanCreations15** [comment]
Doesn't look to be fixed, running 21.1.0 - States item removed, but item is still on the list.

**Comment by SeanCreations15** [comment]
Confirmed by also trying to "re-add" after seeing the "Item removed." message, but no message and no animation of "adding".

**Comment by Jarva** [comment]
Will keep it open, should fix for next release

**Comment by sciwhiz12** [comment]
This isn't inherently a bug in Ars Additions, but a bug in Ars Nouveau's void jar, which the Jar of Miner's Wisdom (`XpJar`) extends from. See https://github.com/baileyholl/Ars-Nouveau/issues/1429 and https://github.com/baileyholl/Ars-Nouveau/pull/1455 for details.

**Comment by SeanCreations15** [comment]
I raised the same issue over on Ars-Nouveua for the Void Jar as I know Miner's Wisdom inherits the Void Jar.

**Comment by Jarva** [comment]
Resolved with Ars 5.2.2 release
