### ISSUE TITLE
Both Craftoria and Allthemods10 servers crashing with this mod in it

### ISSUE THREAD

**Issue by Cebio** [Jarva/Ars-Additions#7]
Hi, Im new to the modding both modpacks are crashing with this in it and i dont know how to solve.
[crash-2024-10-12_02.46.38-fml.txt](https://github.com/user-attachments/files/17348108/crash-2024-10-12_02.46.38-fml.txt)
[crash-2024-10-12_01.11.32-fml.txt](https://github.com/user-attachments/files/17348109/crash-2024-10-12_01.11.32-fml.txt)

**Comment by Jarva** [comment]
This is due to the language being in Turkish, should be fixed on 21.1.0

Apologies for the late response, I didn't see the issue raised, for faster responses I recommend joining my discord server.

https://discord.gg/kxUxmhQguE

**Comment by Cebio** [comment]
No problem at all they mentioned it in other hubs and it got solved thank you anyway.
