### ISSUE TITLE
Magelights count as entities - do they count in the new lanterns?

### ISSUE THREAD

**Issue by SometimesClueless** [Jarva/Ars-Additions#9]
Hello,

I'm wondering if your magelight lanterns fix the issue where magelights count as entities? This mod is being added to the Cisco Medieval Ultimate modpack and my team is hosting it as a server for players to play on. I would like to prevent any lag caused by the magelight entities.

If this does not stop it, could it be done so for the future?

**Comment by Jarva** [comment]
Hi there, the magelight lanterns in Ars Additions are block entities that use particles so no additional entities are created. It should be the same level of impact as an empty chest

**Comment by SometimesClueless** [comment]
Oh brilliant! Hopefully that means we can actually spam them around a base to light it up like torches do without a problem then?

**Comment by Jarva** [comment]
Yes that should be fine, any lag experienced would likely be clientside due to the particles
